############## Reference to configuration files ###################################
	CLS

	$ConfigRootFOlder = $env:Powershell_ConfigRootLocation

	Set-Location $ConfigRootFOlder
	. .\ConnectionStrings.config.ps1
	. .\IOFunctions.ps1
	. .\DirLocations.Config.ps1
	. .\fGenericImportJob.ps1
	. .\fGenericNormalization.ps1
#################################################################################### 


#****** Initialize other variables ******
	$strDateNow = get-date -format "yyyyMMddTHHmmss"
	$PSScriptName 	= $MyInvocation.MyCommand.Name.ToString()
	$PSScriptName 	= $PSScriptName.Replace(".ps1","")
	$LogFile = "$dirLogFolder\$PSScriptName."+$strDateNow+".txt"
	$ReturnDate = ""


	$strDateYear = get-date -format "yyyy"
	$strDateMonth = get-date -format "MM"
	$strDateToday = get-date -format "yyyyMMdd"
	$dirRawFiles = "$dirServicesDeliveryStoreFolder\MSCI LRMP"
	$dirComplianceGdriveFolder = "\\hcmlp.com\data\public\Retail Funds\FUNDS\Other\Illiquid Securities\Liquidity Risk Management Program (LRMP)\MSCI\22e4 MSCI Daily Reporting Archive"
	$dirComplianceGdriveFolderToday = "$dirComplianceGdriveFolder\$strDateYear\$strDateMonth\$strDateToday"
	$dirComplianceGdriveFolderTodayArchive = "$dirComplianceGdriveFolderToday\$strDateNow"
	$dirEmailRiskCommittee = "$dirRawFiles\Email Reports - Liquidity Risk Committee"
	$dirEmailFFA = "$dirRawFiles\Email Reports - FFA"

	#We don't need the cntl files - they are system files generated by MSCI that have no meaning to anyone but them
	Remove-Item "$dirRawFiles\*.cntl"

	if(!(Test-Path -Path $dirComplianceGdriveFolderToday )){
	    New-Item -ItemType directory -Path $dirComplianceGdriveFolderToday
	}
	else {
		New-Item -ItemType directory -Path $dirComplianceGdriveFolderTodayArchive
	
		Move-Item "$dirComplianceGdriveFolderToday\*.*" $dirComplianceGdriveFolderTodayArchive
	}
	
	Copy-Item "$dirRawFiles\*.*" $dirComplianceGdriveFolderToday
	
	Copy-Item "$dirRawFiles\*.pdf" $dirEmailRiskCommittee

	Copy-Item "$dirRawFiles\*HIGHLAND_TOTAL_RETURN*.pdf" $dirEmailFFA
	Copy-Item "$dirRawFiles\*HIGHLAND_FIXED_INCOME*.pdf" $dirEmailFFA
	
#****** Generic Import ******
	$GenericImportJobID = 147
	fGenericImportJob $GenericImportJobID -pDirSourceFolder $null -pRefDataSetDate $null -pLabel $null -pLogFile $LogFile -pFileName $null -pDirArchiveFolder $null ([Ref]$ReturnDate)
	$GenericImportJobID = 148
	fGenericImportJob $GenericImportJobID -pDirSourceFolder $null -pRefDataSetDate $null -pLabel $null -pLogFile $LogFile -pFileName $null -pDirArchiveFolder $null ([Ref]$ReturnDate)

	#WILL DELETE THE Remove-Item COMMAND ONCE WE START LOADING THE FILES INTO THE DB AND ARCHIVING
	Remove-Item "$dirRawFiles\*.*"



##****** Generic Normalization ******
#	$RefDatasetDate = $ReturnDate
#	fGenericNormalization -pGenericNormaliztaionJobID $GenericNormaliztaionJobID -pRefDatasetDate $RefDatasetDate -pLogFile $LogFile -pScriptName $null
#